# Generated by Django 2.1.3 on 2018-11-16 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20181116_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='files',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
