# Generated by Django 2.1.3 on 2018-11-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20181116_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(blank=True, choices=[('image', 'image'), ('video', 'video'), ('pdf', 'pdf'), ('audio', 'audio')], max_length=10),
        ),
    ]
