# Generated by Django 2.1.3 on 2018-11-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(blank=True, choices=[('image', 'image'), ('video', 'video'), ('pdf', 'pdf'), ('audio', 'audio'), ('other', 'other')], max_length=10),
        ),
    ]
