# Generated by Django 2.1.3 on 2018-11-29 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0010_auto_20181129_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owners', 'The owners'), ('editors', 'The editors'), ('admins', 'The admins'), ('users', 'Any logged in users'), ('visitors', 'Any visitors to the website can')], max_length=200)),
                ('action', models.CharField(choices=[('create', 'create a new object'), ('edit', 'edit the object'), ('view', 'view the object'), ('delete', 'delete the object')], max_length=200)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owners', 'The owners'), ('editors', 'The editors'), ('admins', 'The admins'), ('users', 'Any logged in users'), ('visitors', 'Any visitors to the website can')], max_length=200)),
                ('action', models.CharField(choices=[('create', 'create a new object'), ('edit', 'edit the object'), ('view', 'view the object'), ('delete', 'delete the object')], max_length=200)),
                ('allowed', models.BooleanField(default=False)),
            ],
        ),
    ]
