# Generated by Django 2.1.3 on 2018-11-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimewiki_auth', '0002_auto_20181129_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionstrategy',
            name='description',
            field=models.CharField(default='t', max_length=200),
            preserve_default=False,
        ),
    ]
