# Generated by Django 2.1.3 on 2018-11-29 18:22

from django.db import migrations
from crimewiki_auth.models import PERMISSION_STRATEGIES


def edit_permission_strategies(apps, schema_editor):
    PermissionStrategy = apps.get_model('crimewiki_auth', 'PermissionStrategy')
    for s in PERMISSION_STRATEGIES:
        ps = PermissionStrategy.objects.get(
            role=s['role'], action=s['action'], allowed=s['allowed'])
        ps.description = s['description']
        ps.save()


class Migration(migrations.Migration):

    dependencies = [
        ('crimewiki_auth', '0004_auto_20181129_1219'),
    ]

    operations = [
        migrations.RunPython(edit_permission_strategies)
    ]
