# Generated by Django 2.1.3 on 2018-11-20 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', models.TextField()),
            ],
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('type', models.CharField(blank=True, choices=[('image', 'image'), ('video', 'video'), ('pdf', 'pdf'), ('audio', 'audio'), ('other', 'other')], max_length=10)),
                ('file_path', models.FileField(upload_to='')),
            ],
            bases=('pages.page',),
        ),
        migrations.RemoveField(
            model_name='page',
            name='files',
        ),
    ]
